import { useQueryAllPosts } from '@/hooks/useQueryAllPosts';
import { useQueryUserPost } from '@/hooks/useQueryUserPost';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  const { data: userPost } = useQueryUserPost();
  console.log('userPost', userPost);
  const { data: allPosts } = useQueryAllPosts();
  console.log('allPosts', allPosts);

  return (
    <>
      <Head>
        <title>NostalgicMoments</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>TOP</h1>
        <Link href="auth">ログイン</Link>
      </main>
    </>
  );
}
